node {
	def commit_id
	stage('Preparation'){
		checkout scm
		sh "git rev-parse --short HEAD > .git/commit-id"
		commit_id = readFile('.git/commit-id').trim()
	}
	stage('test'){
		nodejs(nodeJSInstallationName: 'nodejs'){
			sh 'npm install --save-dev --only=dev'
			sh 'npm test'
		}
	}
}
